spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mock?useUnicode=true&characterEncoding=UTF-8
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
